### ISSUE TITLE
get profile by `api_key`

### ISSUE THREAD

**Issue by zalog** [civictechro/DSU-reportapp-api#72]
Am văzut endpointul `/utilizator/{id}`, dar acolo e nevoie de id. După logare, aplicația nu știe id-ul userului,
avem doar api_key.

Cred că ar fi mai curat să facem un endpoint get/post `/profile`, doar pe baza api_key. Nu?

**Comment by tudor-rusu** [comment]
branch https://github.com/civictechro/DSU-reportapp-api/tree/feature/72_Get_user_profile

**Comment by zalog** [comment]
Tnks! Revin daca e cazul.

**Comment by tudor-rusu** [comment]
master-ul nu este inca updatat, lucreaza de pe staging cu features

**Comment by zalog** [comment]
Ah, înțeleg.
Lasă că oricum nu pot consuma endpointurile local.
Vedem când termini și se cred că se ocupă Lucian.
