### ISSUE TITLE
endpoint "/reset-password"

### ISSUE THREAD

**Issue by zalog** [civictechro/DSU-reportapp-api#73]
Am găsit `/utilizator/resetare-parola` dar acoperă doar cazul în care utilizatorul vrea să reseteze parola logat fiind.

Avem nevoie de un endpoint pentru a putea reseta parola din ecranul de login, înainte ca userul să fie autentificat. Un `/reset-password`.

**Comment by lucianstuparu** [comment]
Am adaugat un nou endpoint, `/utilizator/am-uitat-parola`.
La request de POST cu adresa de email pentru care se doreste resetarea parolei, utilizatorul primeste un email cu un link de resetare (token generat, care expira la 60 minute).
`{
  "email": "user@user.com"
}`
Continuarea procesului de resetare (introducere parola noua), urmeaza a fi dezvoltata separat.
